server:
  port: 8082
  servlet:
    context-path: /zll
student:
  name: 王帅111
  age: 18
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&aserverTimezone=UTC
#    url: jdbc:mysql:///blog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&aserverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zll.blog.pojo